### ISSUE TITLE
Management buttons

### ISSUE THREAD

**Issue by ckcollab** [codalab/chahub#133]
Add buttons allowing an admin to modify/remove/add listings.

When an admin is logged in listings should show a pencil (edit) and x (delete) button. The buttons should only show when hovered. Clicking edit brings up a modal form for listings. When the form is successfully submitted it should be cleared. Errors for the form should be shown inline, if possible

The modal form can also be used for creation. The creation button should be fixed to the bottom right of the viewport.

**Comment by BrendanMyers88** [comment]
### Todo:

- [ ] (+) button on bottom right, fixed
- [ ] (+) button click opens modal
- [ ] modal created with fields: title, description, logo url (eep, we need to make this download and process image still... TODO!) (producer dropdown... if we create a new competition it _has_ to be long to a producer)
- [ ] Clicking edit on competition loads details in modal (you can do `RIOT_OBSERVABLE.trigger('competition_selected', event.item.competition_or_whatever_it_is)`
- [ ] (ERIC/CHRIS/TYLER/JIMMY) Clicking save in the modal POSTS the competition
